---
  - name: apt update
    apt:
      update_cache: true
      cache_valid_time: 3600 
      force_apt_get: true

  - name: apt upgrade
    apt:
      upgrade: dist
      force_apt_get: true

  - name: Install common packages
    apt:  
      name: "{{ item }}"
      state: latest
    loop:
      - "{{ common_packages }}"