---
  - name: Create 'probe' group
    group:
      name: probe
      state: present

  - name: Add 'probe' group to sudoers
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%probe'
      line: '%probe ALL=(ALL:ALL) ALL'
      validate: 'visudo -cf %s'

  - name: Create probe user
    user:
      name: probe
      password: $6$SALTsalt$m/ttv3O.Rgv4ouf2Jmoihkj28jhiBEGCVkhgEvWY0yearAO9r4HA9iqIRLdx6d1tmw.cJw0/LLA66sZr4a2nf1
      groups: probe
      state: present

  - name: Create home directory for probe user
    file:
      path: /home/probe/probe
      state: directory
      owner: probe
      group: probe
      mode: '0755'
