---
  - name: Copy firstboot setup script
    copy:    
      src: setup-file.sh
      dest: /boot/overlays/setup-file.sh

  - name: Copy list for ooni
    copy:    
      src: list.txt
      dest: /boot/overlays/list.txt
      mode: '0777'

  - name: Copy PiProbe.conf file
    copy:    
      src: PiProbe.conf.example
      dest: /boot/overlays/PiProbe.conf.example

  - name: Edit /etc/rc.local to run setup-file.sh when booting
    lineinfile:
      dest: /etc/rc.local
      insertbefore: 'exit 0'
      line: "sudo bash /boot/overlays/setup-file.sh &"