---
  - name: Copy ooniprobe config file
    copy:    
      src: setup-file.sh
      dest: /boot/overlays/setup-file.sh
      owner: probe
      group: probe
      mode: '0755'

  - name: Copy list for ooni
    copy:    
      src: list.txt
      dest: /boot/overlays/list.txt
      owner: probe
      group: probe
      mode: '0755'

  - name: Edit /etc/rc.local to run setup-file.sh when booting
    lineinfile:
      dest: /etc/rc.local
      insertbefore: 'exit 0'
      line: "sudo bash /boot/overlays/setup-file.sh &"